name: Cisco IOS CI

on:
  push:
    paths:
      - 'tests/cisco/ios/**'
      - 'cve/cisco/ios/**'
  pull_request:
    paths:
      - 'tests/cisco/ios/**'
      - 'cve/cisco/ios/**'

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run YAML tests
      run: |
        for test in tests/cisco/ios/*.yaml; do
          echo "Running test: $test"
          bash /root/cve/.git/hooks/pre-commit "$test"
        done