name: Run YAML tests

on:
  push:
  pull_request:

jobs:
  run-test-job:
    runs-on: ubuntu-latest
    container:
      image: netpicker/crt
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Run yaml tests
        run: test-rules --rules-dir rules/ -W ignore::coverage.exceptions.CoverageWarning --cov=./rules -p runner.yaml_rules -vvvl --rootdir $PWD $PWD
